### PR TITLE
Add mock as a test dependency

### PR DESCRIPTION
**Pull request by Natim**
r? @davehunt

### CODE REVIEW

**Comment by davehunt** [comment]
We're using PyFxA from PyPI.. are the _test_ dependencies going to be installed in this scenario?

**Comment by Natim** [comment]
Note that it will add it to the test_requires because of https://github.com/mozilla/PyFxA/blob/master/setup.py#L26-L28

**Comment by davehunt** [comment]
> Note that it will add it to the test_requires because of https://github.com/mozilla/PyFxA/blob/master/setup.py#L26-L28

Right, and we're not running the PyFxA tests here, we're using PyFxA to write our own tests that use PyFxA. We use `TestEmailAccount` [here](https://github.com/mozilla/fxapom/blob/bc7175f5788a9144410739656943cd2e89e30915/fxapom/fxapom.py#L56).

**Comment by Natim** [comment]
Ok so you need to use fxa.tests.utils without PyFxA tests dependencies.
Here is an alternative solution.

**Comment by davehunt** [comment]
@Natim looks good, I'll give this a test shortly and report back!

**Comment by Natim** [comment]
> I'll give this a test shortly and report back!

Thanks

**Comment by davehunt** [comment]
@Natim works perfectly. Could you release a new version once this is merged? Thanks!

**Comment by Natim** [comment]
Sure let's do that :)

**Comment by Natim** [comment]
PyFxA 0.2.0 have been released.

**Pull request merged**
