### PR TITLE
Add retries to the APIClient session

### PR DESCRIPTION
**Pull request by robhudson**
Potential fix for the connection errors.

See https://github.com/mozmeao/basket/issues/1187

### CODE REVIEW

**Review by Natim — APPROVED** [review]
Should we add a test for this too?

**Comment by robhudson** [comment]
I was attempting to, but there are no docs on running the tests and out of the box it runs tests against a server that no longer exists. If I were to add tests I would need some guidance from the FxA team.

**Review by clouserw — APPROVED** [review]

**Comment by robhudson** [comment]
Any chance to publish a new release to PyPI with this change?

**Comment by clouserw** [comment]
I think @Natim is the only still active maintainer.  If this is the only diff I'd be fine with pushing a 0.7.8 out.

@Natim would you add me (clouserw) as a maintainer as well please?

**Comment by Natim** [comment]
I started https://github.com/mozilla/PyFxA/pull/99 however I don't have write access to mozilla/PyFxA to merge it anymore.

**Comment by Natim** [comment]
Yes I guess it makes sense to add you :grinning:

**Comment by clouserw** [comment]
I think you have an invite for write access.  It also said we have limited seats, so, let's see if it works.

**Comment by Natim** [comment]
Yes I received it, do you have access to circle ci by any chance to fix it's access too?

https://app.circleci.com/pipelines/github/mozilla/PyFxA/12/workflows/46c7895a-bb4e-4672-8e6d-151fa1a4b8f8/jobs/23

**Comment by Natim** [comment]
I did the release, you can remove my permission to the github repository til next time, you now have the permission on the pypi project too.

**Comment by clouserw** [comment]
Thanks.  I'll leave you on it unless we run out of seats.

I fixed circleci's access, but it looks like the tests are pretty broken (out of date dependencies, at least on the older python).  Anyway, one step closer.  Thanks for the release @Natim

**Pull request merged**
