### PR TITLE
Cache classes should expose Unicode.

### PR DESCRIPTION
**Pull request by Natim**
Our cache classes should return unicode strings at this stage.

### CODE REVIEW

**Comment by rfk** [comment]
make sense, thanks!

**Comment by Natim** [comment]
Can we release a new version?

**Comment by ametaireau** [comment]
Ideally, we should have rights to push there (I just checked it's not the case).

@rfk can you add us there? thanks!

**Comment by rfk** [comment]
You should have PyPI maintainer rights now

**Comment by rfk** [comment]
I released v0.0.6 to PyPI

**Comment by ametaireau** [comment]
Great thanks!

**Pull request merged**
